// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package apis

import (
	"github.com/chaos-plus/chaos-plus/api/apis"
)

type ControllerV1 struct{}

func NewV1() apis.IApisV1 {
	return &ControllerV1{}
}
