// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package users

import (
	"github.com/chaos-plus/chaos-plus/api/users"
)

type ControllerV1 struct{}

func NewV1() users.IUsersV1 {
	return &ControllerV1{}
}
