package consts

var (
	LICENSE_AES_KEY = "1357924680-YourPa44vvord14VVr0ng"
	JWT_RSA_PRI_KEY = `
-----BEGIN RSA PRIVATE KEY-----
MIICXgIBAAKBgQCzVln7rcsT9wHHmfD+DxY4ElLefT43kSnhpb4O6guIEmq5socN
nVMuwzhp9vU6oxJ8v4qeMX6bj/FHkzdNpySgiUcjieXkhaNS5ZiwW1zvR6soXOI0
gvy5G5oEvEFzBZylYX7Vx6rMZZKJPBPrVDAWLTFL3g2d/UcqXn8XMKoJLQIDAQAB
AoGBAJBYusi21DRXppkQMUdswUeUiBsI1+FF+F3lWBsNCwcVO84IAmhU7zU+cNPp
sOzngOPkECDQWcXAkEY6GlNoazNpIND4oO1fdh+HxVg7ZV1CNOBWbo4lDtExCI9u
KldB8dIS4Vb0NMWqilzUtVlgVhsegrftgkVTrjPjCOUZNjwJAkEA7osj6mLxNySq
CYZjldx3AOrs5XBl5Phq0Yy+FknM0eOxB9s9zC4dz/XeqvLOldQPUEnJgEmlOdwn
bHMUQFhLcwJBAMB2C7W/s4aKY7kif9xy/BuHWf7ttBUdz/lYqVZH6YrAnNEMDVx2
bovn2m64Wm/+lBqd7LmsFLAuxHh7sJ7KcN8CQQCyJOkyjqeTxebSbDGM5nNdFRTL
mDAQWlDzo4cGACFdEgzQUDQLetk6yGR9CA2tqQuyqxg3nUguOLKcdCjIkOfvAkAH
2Yi2u//lf+V7WpXedu4jbUzVYfqTVejyoZQeicZTu3Fp8VTmLYpquGUnWOuPX9HI
mCJcnFEnsnCe/WSBxX3/AkEAsekg2JQ7vXkPSt5BSCs37tNFmynCqfrGlmsgfpQr
iUw+JBQFGjBxxx3VFWcpUN3Oh7yHETPxDG0IBQrHRyGxFQ==
-----END RSA PRIVATE KEY-----	
`
	JWT_RSA_PUB_KEY = `
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCzVln7rcsT9wHHmfD+DxY4ElLe
fT43kSnhpb4O6guIEmq5socNnVMuwzhp9vU6oxJ8v4qeMX6bj/FHkzdNpySgiUcj
ieXkhaNS5ZiwW1zvR6soXOI0gvy5G5oEvEFzBZylYX7Vx6rMZZKJPBPrVDAWLTFL
3g2d/UcqXn8XMKoJLQIDAQAB
-----END PUBLIC KEY-----
`
	AUTH_WHITE_LIST = []string{
		"POST:/v1/tokens",
	}
)
