// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package plugins

import (
	"github.com/chaos-plus/chaos-plus/api/plugins"
)

type ControllerV1 struct{}

func NewV1() plugins.IPluginsV1 {
	return &ControllerV1{}
}
