// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package plugin_repos

import (
	"github.com/chaos-plus/chaos-plus/api/plugin_repos"
)

type ControllerV1 struct{}

func NewV1() plugin_repos.IPluginReposV1 {
	return &ControllerV1{}
}
