// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalAuthTokensDao is an internal type for wrapping the internal DAO implementation.
type internalAuthTokensDao = *internal.AuthTokensDao

// authTokensDao is the data access object for the table chaosplus_auth_tokens.
// You can define custom methods on it to extend its functionality as needed.
type authTokensDao struct {
	internalAuthTokensDao
}

var (
	// AuthTokens is a globally accessible object for table chaosplus_auth_tokens operations.
	AuthTokens = authTokensDao{
		internal.NewAuthTokensDao(),
	}
)

// Add your custom methods and functionality below.
