// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalCasbinRulesDao is an internal type for wrapping the internal DAO implementation.
type internalCasbinRulesDao = *internal.CasbinRulesDao

// casbinRulesDao is the data access object for the table chaosplus_casbin_rules.
// You can define custom methods on it to extend its functionality as needed.
type casbinRulesDao struct {
	internalCasbinRulesDao
}

var (
	// CasbinRules is a globally accessible object for table chaosplus_casbin_rules operations.
	CasbinRules = casbinRulesDao{
		internal.NewCasbinRulesDao(),
	}
)

// Add your custom methods and functionality below.
