// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalChangeLogsDao is an internal type for wrapping the internal DAO implementation.
type internalChangeLogsDao = *internal.ChangeLogsDao

// changeLogsDao is the data access object for the table chaosplus_change_logs.
// You can define custom methods on it to extend its functionality as needed.
type changeLogsDao struct {
	internalChangeLogsDao
}

var (
	// ChangeLogs is a globally accessible object for table chaosplus_change_logs operations.
	ChangeLogs = changeLogsDao{
		internal.NewChangeLogsDao(),
	}
)

// Add your custom methods and functionality below.
