// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalDistributedLocksDao is an internal type for wrapping the internal DAO implementation.
type internalDistributedLocksDao = *internal.DistributedLocksDao

// distributedLocksDao is the data access object for the table chaosplus_distributed_locks.
// You can define custom methods on it to extend its functionality as needed.
type distributedLocksDao struct {
	internalDistributedLocksDao
}

var (
	// DistributedLocks is a globally accessible object for table chaosplus_distributed_locks operations.
	DistributedLocks = distributedLocksDao{
		internal.NewDistributedLocksDao(),
	}
)

// Add your custom methods and functionality below.
