// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalDistributedLockDao is an internal type for wrapping the internal DAO implementation.
type internalDistributedLockDao = *internal.DistributedLockDao

// distributedLockDao is the data access object for the table chaosplus_distributed_lock.
// You can define custom methods on it to extend its functionality as needed.
type distributedLockDao struct {
	internalDistributedLockDao
}

var (
	// DistributedLock is a globally accessible object for table chaosplus_distributed_lock operations.
	DistributedLock = distributedLockDao{
		internal.NewDistributedLockDao(),
	}
)

// Add your custom methods and functionality below.
