// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalFilesDao is an internal type for wrapping the internal DAO implementation.
type internalFilesDao = *internal.FilesDao

// filesDao is the data access object for the table chaosplus_files.
// You can define custom methods on it to extend its functionality as needed.
type filesDao struct {
	internalFilesDao
}

var (
	// Files is a globally accessible object for table chaosplus_files operations.
	Files = filesDao{
		internal.NewFilesDao(),
	}
)

// Add your custom methods and functionality below.
