// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalFilesClosureDao is an internal type for wrapping the internal DAO implementation.
type internalFilesClosureDao = *internal.FilesClosureDao

// filesClosureDao is the data access object for the table chaosplus_files_closure.
// You can define custom methods on it to extend its functionality as needed.
type filesClosureDao struct {
	internalFilesClosureDao
}

var (
	// FilesClosure is a globally accessible object for table chaosplus_files_closure operations.
	FilesClosure = filesClosureDao{
		internal.NewFilesClosureDao(),
	}
)

// Add your custom methods and functionality below.
