// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalFileStoragesDao is an internal type for wrapping the internal DAO implementation.
type internalFileStoragesDao = *internal.FileStoragesDao

// fileStoragesDao is the data access object for the table chaosplus_file_storages.
// You can define custom methods on it to extend its functionality as needed.
type fileStoragesDao struct {
	internalFileStoragesDao
}

var (
	// FileStorages is a globally accessible object for table chaosplus_file_storages operations.
	FileStorages = fileStoragesDao{
		internal.NewFileStoragesDao(),
	}
)

// Add your custom methods and functionality below.
