// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalFileUploadingPartsDao is an internal type for wrapping the internal DAO implementation.
type internalFileUploadingPartsDao = *internal.FileUploadingPartsDao

// fileUploadingPartsDao is the data access object for the table chaosplus_file_uploading_parts.
// You can define custom methods on it to extend its functionality as needed.
type fileUploadingPartsDao struct {
	internalFileUploadingPartsDao
}

var (
	// FileUploadingParts is a globally accessible object for table chaosplus_file_uploading_parts operations.
	FileUploadingParts = fileUploadingPartsDao{
		internal.NewFileUploadingPartsDao(),
	}
)

// Add your custom methods and functionality below.
