// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalFileUploadingTasksDao is an internal type for wrapping the internal DAO implementation.
type internalFileUploadingTasksDao = *internal.FileUploadingTasksDao

// fileUploadingTasksDao is the data access object for the table chaosplus_file_uploading_tasks.
// You can define custom methods on it to extend its functionality as needed.
type fileUploadingTasksDao struct {
	internalFileUploadingTasksDao
}

var (
	// FileUploadingTasks is a globally accessible object for table chaosplus_file_uploading_tasks operations.
	FileUploadingTasks = fileUploadingTasksDao{
		internal.NewFileUploadingTasksDao(),
	}
)

// Add your custom methods and functionality below.
