// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalLabelsDao is an internal type for wrapping the internal DAO implementation.
type internalLabelsDao = *internal.LabelsDao

// labelsDao is the data access object for the table chaosplus_labels.
// You can define custom methods on it to extend its functionality as needed.
type labelsDao struct {
	internalLabelsDao
}

var (
	// Labels is a globally accessible object for table chaosplus_labels operations.
	Labels = labelsDao{
		internal.NewLabelsDao(),
	}
)

// Add your custom methods and functionality below.
