// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalLogsDao is internal type for wrapping internal DAO implements.
type internalLogsDao = *internal.LogsDao

// logsDao is the data access object for table logs.
// You can define custom methods on it to extend its functionality as you wish.
type logsDao struct {
	internalLogsDao
}

var (
	// Logs is globally public accessible object for table logs operations.
	Logs = logsDao{
		internal.NewLogsDao(),
	}
)

// Fill with you ideas below.
