// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalPermissionsAdditionalDao is an internal type for wrapping the internal DAO implementation.
type internalPermissionsAdditionalDao = *internal.PermissionsAdditionalDao

// permissionsAdditionalDao is the data access object for the table chaosplus_permissions_additional.
// You can define custom methods on it to extend its functionality as needed.
type permissionsAdditionalDao struct {
	internalPermissionsAdditionalDao
}

var (
	// PermissionsAdditional is a globally accessible object for table chaosplus_permissions_additional operations.
	PermissionsAdditional = permissionsAdditionalDao{
		internal.NewPermissionsAdditionalDao(),
	}
)

// Add your custom methods and functionality below.
