// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalPluginResourcesDao is an internal type for wrapping the internal DAO implementation.
type internalPluginResourcesDao = *internal.PluginResourcesDao

// pluginResourcesDao is the data access object for the table chaosplus_plugin_resources.
// You can define custom methods on it to extend its functionality as needed.
type pluginResourcesDao struct {
	internalPluginResourcesDao
}

var (
	// PluginResources is a globally accessible object for table chaosplus_plugin_resources operations.
	PluginResources = pluginResourcesDao{
		internal.NewPluginResourcesDao(),
	}
)

// Add your custom methods and functionality below.
