// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalPluginReposDao is an internal type for wrapping the internal DAO implementation.
type internalPluginReposDao = *internal.PluginReposDao

// pluginReposDao is the data access object for the table chaosplus_plugin_repos.
// You can define custom methods on it to extend its functionality as needed.
type pluginReposDao struct {
	internalPluginReposDao
}

var (
	// PluginRepos is a globally accessible object for table chaosplus_plugin_repos operations.
	PluginRepos = pluginReposDao{
		internal.NewPluginReposDao(),
	}
)

// Add your custom methods and functionality below.
