// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalPluginsDao is an internal type for wrapping the internal DAO implementation.
type internalPluginsDao = *internal.PluginsDao

// pluginsDao is the data access object for the table chaosplus_plugins.
// You can define custom methods on it to extend its functionality as needed.
type pluginsDao struct {
	internalPluginsDao
}

var (
	// Plugins is a globally accessible object for table chaosplus_plugins operations.
	Plugins = pluginsDao{
		internal.NewPluginsDao(),
	}
)

// Add your custom methods and functionality below.
