// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalResourcesDao is an internal type for wrapping the internal DAO implementation.
type internalResourcesDao = *internal.ResourcesDao

// resourcesDao is the data access object for the table chaosplus_resources.
// You can define custom methods on it to extend its functionality as needed.
type resourcesDao struct {
	internalResourcesDao
}

var (
	// Resources is a globally accessible object for table chaosplus_resources operations.
	Resources = resourcesDao{
		internal.NewResourcesDao(),
	}
)

// Add your custom methods and functionality below.
