// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalRolesClosureDao is an internal type for wrapping the internal DAO implementation.
type internalRolesClosureDao = *internal.RolesClosureDao

// rolesClosureDao is the data access object for the table chaosplus_roles_closure.
// You can define custom methods on it to extend its functionality as needed.
type rolesClosureDao struct {
	internalRolesClosureDao
}

var (
	// RolesClosure is a globally accessible object for table chaosplus_roles_closure operations.
	RolesClosure = rolesClosureDao{
		internal.NewRolesClosureDao(),
	}
)

// Add your custom methods and functionality below.
