// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalSettingsDao is an internal type for wrapping the internal DAO implementation.
type internalSettingsDao = *internal.SettingsDao

// settingsDao is the data access object for the table chaosplus_settings.
// You can define custom methods on it to extend its functionality as needed.
type settingsDao struct {
	internalSettingsDao
}

var (
	// Settings is a globally accessible object for table chaosplus_settings operations.
	Settings = settingsDao{
		internal.NewSettingsDao(),
	}
)

// Add your custom methods and functionality below.
