// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalTSequenceDao is an internal type for wrapping the internal DAO implementation.
type internalTSequenceDao = *internal.TSequenceDao

// tSequenceDao is the data access object for the table t_sequence.
// You can define custom methods on it to extend its functionality as needed.
type tSequenceDao struct {
	internalTSequenceDao
}

var (
	// TSequence is a globally accessible object for table t_sequence operations.
	TSequence = tSequenceDao{
		internal.NewTSequenceDao(),
	}
)

// Add your custom methods and functionality below.
