// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalTenantsDao is an internal type for wrapping the internal DAO implementation.
type internalTenantsDao = *internal.TenantsDao

// tenantsDao is the data access object for the table chaosplus_tenants.
// You can define custom methods on it to extend its functionality as needed.
type tenantsDao struct {
	internalTenantsDao
}

var (
	// Tenants is a globally accessible object for table chaosplus_tenants operations.
	Tenants = tenantsDao{
		internal.NewTenantsDao(),
	}
)

// Add your custom methods and functionality below.
