// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalTenantDao is an internal type for wrapping the internal DAO implementation.
type internalTenantDao = *internal.TenantDao

// tenantDao is the data access object for the table chaosplus_tenant.
// You can define custom methods on it to extend its functionality as needed.
type tenantDao struct {
	internalTenantDao
}

var (
	// Tenant is a globally accessible object for table chaosplus_tenant operations.
	Tenant = tenantDao{
		internal.NewTenantDao(),
	}
)

// Add your custom methods and functionality below.
