// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalTerminalsDao is an internal type for wrapping the internal DAO implementation.
type internalTerminalsDao = *internal.TerminalsDao

// terminalsDao is the data access object for the table chaosplus_terminals.
// You can define custom methods on it to extend its functionality as needed.
type terminalsDao struct {
	internalTerminalsDao
}

var (
	// Terminals is a globally accessible object for table chaosplus_terminals operations.
	Terminals = terminalsDao{
		internal.NewTerminalsDao(),
	}
)

// Add your custom methods and functionality below.
