// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalUsersRolesDao is an internal type for wrapping the internal DAO implementation.
type internalUsersRolesDao = *internal.UsersRolesDao

// usersRolesDao is the data access object for the table chaosplus_users_roles.
// You can define custom methods on it to extend its functionality as needed.
type usersRolesDao struct {
	internalUsersRolesDao
}

var (
	// UsersRoles is a globally accessible object for table chaosplus_users_roles operations.
	UsersRoles = usersRolesDao{
		internal.NewUsersRolesDao(),
	}
)

// Add your custom methods and functionality below.
