// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalWorkerIdDao is an internal type for wrapping the internal DAO implementation.
type internalWorkerIdDao = *internal.WorkerIdDao

// workerIdDao is the data access object for the table chaosplus_worker_id.
// You can define custom methods on it to extend its functionality as needed.
type workerIdDao struct {
	internalWorkerIdDao
}

var (
	// WorkerId is a globally accessible object for table chaosplus_worker_id operations.
	WorkerId = workerIdDao{
		internal.NewWorkerIdDao(),
	}
)

// Add your custom methods and functionality below.
