// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalWorkerNodeDao is an internal type for wrapping the internal DAO implementation.
type internalWorkerNodeDao = *internal.WorkerNodeDao

// workerNodeDao is the data access object for the table chaosplus_worker_node.
// You can define custom methods on it to extend its functionality as needed.
type workerNodeDao struct {
	internalWorkerNodeDao
}

var (
	// WorkerNode is a globally accessible object for table chaosplus_worker_node operations.
	WorkerNode = workerNodeDao{
		internal.NewWorkerNodeDao(),
	}
)

// Add your custom methods and functionality below.
