// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/chaos-plus/chaos-plus/internal/dao/internal"
)

// internalWorkerIdsDao is an internal type for wrapping the internal DAO implementation.
type internalWorkerIdsDao = *internal.WorkerIdsDao

// workerIdsDao is the data access object for the table chaosplus_worker_ids.
// You can define custom methods on it to extend its functionality as needed.
type workerIdsDao struct {
	internalWorkerIdsDao
}

var (
	// WorkerIds is a globally accessible object for table chaosplus_worker_ids operations.
	WorkerIds = workerIdsDao{
		internal.NewWorkerIdsDao(),
	}
)

// Add your custom methods and functionality below.
